import { Component, Input } from '@angular/core';
import { GrpValueService } from 'src/app/service/grp-value.service';
import { MymatchesService } from 'src/app/service/mymatches.service';
import {} from "../bet/bet.component";
import { MatchInteface} from "src/app/matches/match.inteface";
import { NgModelGroup } from '@angular/forms';

@Component({
  selector: 'app-match',
  templateUrl: './match.component.html',
  styleUrls: ['./match.component.css']
})
export class MatchComponent {

  constructor(private readonly _serv: GrpValueService,public readonly M_serv:MymatchesService ){}

  public get grp() {
    return this._serv.group;
  }

  MgrpTab:MatchInteface[]=[];


   Mgrp={
    "name": "World Cup 2022",
    "matches": [
      {
        "round": "Matchday 1",
        "group": "Group A",
        "date": "2022-11-20",
        "team1": "Qatar",
        "team1img": "https://cloudinary.fifa.com/api/v3/picture/flags-sq-4/QAT?tx=c_fill,g_auto,q_auto,w_94,h_62",
        "team2img": "https://cloudinary.fifa.com/api/v3/picture/flags-sq-4/ECU?tx=c_fill,g_auto,q_auto,w_94,h_62",
        "team2": "Ecuador",
        "cout1": 5.4,
        "coutx": 3.3,
        "cout2": 1.4,
        "Choice": "",
        "bet": 15
      },
      {
        "round": "Matchday 2",
        "group": "Group A",
        "date": "2022-11-21",
        "team1": "Senegal",
        "team1img": "https://cloudinary.fifa.com/api/v3/picture/flags-sq-4/SEN?tx=c_fill,g_auto,q_auto,w_94,h_62",
        "team2img": "https://cloudinary.fifa.com/api/v3/picture/flags-sq-4/NED?tx=c_fill,g_auto,q_auto,w_94,h_62",
        "team2": "Netherlands",
        "cout1": 1.4,
        "coutx": 2.3,
        "cout2": 5.4,
        "Choice": "",
        "bet": 12
      },
      {
        "round": "Matchday 6",
        "group": "Group A",
        "date": "2022-11-25",
        "team1img": "https://cloudinary.fifa.com/api/v3/picture/flags-sq-4/QAT?tx=c_fill,g_auto,q_auto,w_94,h_62",
        "team2img": "https://cloudinary.fifa.com/api/v3/picture/flags-sq-4/SEN?tx=c_fill,g_auto,q_auto,w_94,h_62",
        "team1": "Qatar",
        "team2": "Senegal",
        "cout1": 12.4,
        "coutx": 1.3,
        "cout2": 5.4,
        "Choice": "",
        "bet": 14
      },
      {
        "round": "Matchday 6",
        "group": "Group A",
        "date": "2022-11-25",
        "team1img": "https://cloudinary.fifa.com/api/v3/picture/flags-sq-4/NED?tx=c_fill,g_auto,q_auto,w_94,h_62",
        "team2img": "https://cloudinary.fifa.com/api/v3/picture/flags-sq-4/ECU?tx=c_fill,g_auto,q_auto,w_94,h_62",
        "team1": "Netherlands",
        "team2": "Ecuador",
        "cout1": 2.4,
        "coutx": 1.3,
        "cout2": 5.4,
        "Choice": "",
        "bet": 14
      },
      {
        "round": "Matchday 10",
        "group": "Group A",
        "date": "2022-11-29",
        "team1img": "https://cloudinary.fifa.com/api/v3/picture/flags-sq-4/ECU?tx=c_fill,g_auto,q_auto,w_94,h_62",
        "team2img": "https://cloudinary.fifa.com/api/v3/picture/flags-sq-4/SEN?tx=c_fill,g_auto,q_auto,w_94,h_62",
        "team1": "Ecuador",
        "team2": "Senegal",
        "cout1": 2.9,
        "coutx": 1.5,
        "Choice": "",
        "cout2": 7.4,
        "bet": 11
      },
      {
        "round": "Matchday 10",
        "group": "Group A",
        "date": "2022-11-29",
        "team1img": "https://cloudinary.fifa.com/api/v3/picture/flags-sq-4/NED?tx=c_fill,g_auto,q_auto,w_94,h_62",
        "team2img": "https://cloudinary.fifa.com/api/v3/picture/flags-sq-4/QAT?tx=c_fill,g_auto,q_auto,w_94,h_62",
        "team1": "Netherlands",
        "team2": "Qatar",
        "cout1": 7.4,
        "coutx": 2.3,
        "Choice": "",
        "cout2": 1.4,
        "bet": 4
      },
      {
        "round": "Matchday 2",
        "group": "Group B",
        "date": "2022-11-21",
        "team1img": "https://cloudinary.fifa.com/api/v3/picture/flags-sq-4/ENG?tx=c_fill,g_auto,q_auto,w_94,h_62",
        "team2img": "https://cloudinary.fifa.com/api/v3/picture/flags-sq-4/IRN?tx=c_fill,g_auto,q_auto,w_94,h_62",
        "team1": "England",
        "team2": "Iran",
        "cout1": 4.5,
        "coutx": 3.4,
        "Choice": "",
        "cout2": 3.6,
        "bet": 9
      },
      {
        "round": "Matchday 2",
        "group": "Group B",
        "date": "2022-11-21",
        "team1img": "https://cloudinary.fifa.com/api/v3/picture/flags-sq-4/USA?tx=c_fill,g_auto,q_auto,w_94,h_62",
        "team2img": "https://cloudinary.fifa.com/api/v3/picture/flags-sq-4/WAL?tx=c_fill,g_auto,q_auto,w_94,h_62",
        "team1": "United States",
        "team2": "Wales",
        "cout1": 6.4,
        "coutx": 4.67,
        "Choice": "",
        "cout2": 5.8,
        "bet": 22
      },
      {
        "round": "Matchday 6",
        "group": "Group B",
        "date": "2022-11-25",
        "team1img": "https://cloudinary.fifa.com/api/v3/picture/flags-sq-4/WAL?tx=c_fill,g_auto,q_auto,w_94,h_62",
        "team2img": "https://cloudinary.fifa.com/api/v3/picture/flags-sq-4/IRN?tx=c_fill,g_auto,q_auto,w_94,h_62",
        "team1": "Wales",
        "team2": "Iran",
        "cout1": 8.5,
        "coutx": 5.6,
        "Choice": "",
        "cout2": 2.4,
        "bet": 21
      },
      {
        "round": "Matchday 6",
        "group": "Group B",
        "date": "2022-11-25",
        "team1img": "https://cloudinary.fifa.com/api/v3/picture/flags-sq-4/ENG?tx=c_fill,g_auto,q_auto,w_94,h_62",
        "team2img": "https://cloudinary.fifa.com/api/v3/picture/flags-sq-4/USA?tx=c_fill,g_auto,q_auto,w_94,h_62",
        "team1": "England",
        "team2": "United States",
        "cout1": 1.8,
        "coutx": 4.1,
        "Choice": "",
        "cout2": 2.2,
        "bet": 23
      },
      {
        "round": "Matchday 10",
        "group": "Group B",
        "team1img": "https://cloudinary.fifa.com/api/v3/picture/flags-sq-4/WAL?tx=c_fill,g_auto,q_auto,w_94,h_62",
        "team2img": "https://cloudinary.fifa.com/api/v3/picture/flags-sq-4/ENG?tx=c_fill,g_auto,q_auto,w_94,h_62",
        "date": "2022-11-29",
        "team1": "Wales",
        "team2": "England",
        "cout1": 1.4,
        "coutx": 1.7,
        "Choice": "",
        "cout2": 6.4,
        "bet": 34
      },
      {
        "round": "Matchday 10",
        "group": "Group B",
        "date": "2022-11-29",
        "team1img": "https://cloudinary.fifa.com/api/v3/picture/flags-sq-4/IRN?tx=c_fill,g_auto,q_auto,w_94,h_62",
        "team2img": "https://cloudinary.fifa.com/api/v3/picture/flags-sq-4/USA?tx=c_fill,g_auto,q_auto,w_94,h_62",
        "team1": "Iran",
        "team2": "United States",
        "cout1": 2.4,
        "coutx": 1.3,
        "cout2": 5.4,
        "Choice": "",
        "bet": 56
      },
      {
        "round": "Matchday 3",
        "group": "Group C",
        "date": "2022-11-22",
        "team1img": "https://cloudinary.fifa.com/api/v3/picture/flags-sq-4/ARG?tx=c_fill,g_auto,q_auto,w_94,h_62",
        "team2img": "https://cloudinary.fifa.com/api/v3/picture/flags-sq-4/KSA?tx=c_fill,g_auto,q_auto,w_94,h_62",
        "team1": "Argentina",
        "team2": "Saudi Arabia",
        "cout1": 1.8,
        "coutx": 4.1,
        "cout2": 2.2,
        "Choice": "",
        "bet": 71
      },
      {
        "round": "Matchday 3",
        "group": "Group C",
        "date": "2022-11-22",
        "team1img": "https://cloudinary.fifa.com/api/v3/picture/flags-sq-4/MEX?tx=c_fill,g_auto,q_auto,w_94,h_62",
        "team2img": "https://cloudinary.fifa.com/api/v3/picture/flags-sq-4/POL?tx=c_fill,g_auto,q_auto,w_94,h_62",
        "team1": "Mexico",
        "team2": "Poland",
        "cout1": 5.8,
        "coutx": 5.7,
        "Choice": "",
        "cout2": 1.5,
        "bet": 17
      },
      {
        "round": "Matchday 7",
        "group": "Group C",
        "date": "2022-11-26",
        "team1img": "https://cloudinary.fifa.com/api/v3/picture/flags-sq-4/POL?tx=c_fill,g_auto,q_auto,w_94,h_62",
        "team2img": "https://cloudinary.fifa.com/api/v3/picture/flags-sq-4/KSA?tx=c_fill,g_auto,q_auto,w_94,h_62",
        "team1": "Poland",
        "team2": "Saudi Arabia",
        "cout1": 4.9,
        "coutx": 1.3,
        "Choice": "",
        "cout2": 2.4,
        "bet": 13
      },
      {
        "round": "Matchday 7",
        "group": "Group C",
        "date": "2022-11-26",
        "team1img": "https://cloudinary.fifa.com/api/v3/picture/flags-sq-4/ARG?tx=c_fill,g_auto,q_auto,w_94,h_62",
        "team2img": "https://cloudinary.fifa.com/api/v3/picture/flags-sq-4/MEX?tx=c_fill,g_auto,q_auto,w_94,h_62",
        "team1": "Argentina",
        "team2": "Mexico",
        "cout1": 5.8,
        "coutx": 1.0,
        "Choice": "",
        "cout2": 3.9,
        "bet": 17
      },
      {
        "round": "Matchday 11",
        "group": "Group C",
        "date": "2022-11-30",
        "team1img": "https://cloudinary.fifa.com/api/v3/picture/flags-sq-4/POL?tx=c_fill,g_auto,q_auto,w_94,h_62",
        "team2img": "https://cloudinary.fifa.com/api/v3/picture/flags-sq-4/ARG?tx=c_fill,g_auto,q_auto,w_94,h_62",
        "team1": "Poland",
        "team2": "Argentina",
        "cout1": 2.4,
        "coutx": 1.3,
        "Choice": "",
        "cout2": 5.4,
        "bet": 19
      },
      {
        "round": "Matchday 11",
        "group": "Group C",
        "date": "2022-11-30",
        "team1img": "https://cloudinary.fifa.com/api/v3/picture/flags-sq-4/KSA?tx=c_fill,g_auto,q_auto,w_94,h_62",
        "team2img": "https://cloudinary.fifa.com/api/v3/picture/flags-sq-4/MEX?tx=c_fill,g_auto,q_auto,w_94,h_62",
        "team1": "Saudi Arabia",
        "team2": "Mexico",
        "cout1": 2.4,
        "coutx": 1.3,
        "Choice": "",
        "cout2": 5.4,
        "bet": 16
      },
      {
        "round": "Matchday 3",
        "group": "Group D",
        "team1img": "https://cloudinary.fifa.com/api/v3/picture/flags-sq-4/DEN?tx=c_fill,g_auto,q_auto,w_94,h_62",
        "team2img": "https://cloudinary.fifa.com/api/v3/picture/flags-sq-4/TUN?tx=c_fill,g_auto,q_auto,w_94,h_62",
        "date": "2022-11-22",
        "team1": "Denmark",
        "team2": "Tunisia",
        "cout1": 2.4,
        "coutx": 1.3,
        "Choice": "",
        "cout2": 5.4,
        "bet": 14
      },
      {
        "round": "Matchday 3",
        "team1img": "https://cloudinary.fifa.com/api/v3/picture/flags-sq-4/FRA?tx=c_fill,g_auto,q_auto,w_94,h_62",
        "team2img": "https://cloudinary.fifa.com/api/v3/picture/flags-sq-4/AUS?tx=c_fill,g_auto,q_auto,w_94,h_62",
        "group": "Group D",
        "date": "2022-11-22",
        "team1": "France",
        "team2": "Australia",
        "cout1": 2.4,
        "coutx": 1.3,
        "Choice": "",
        "cout2": 5.4,
        "bet": 14
      },
      {
        "round": "Matchday 7",
        "group": "Group D",
        "date": "2022-11-26",
        "team1img": "https://cloudinary.fifa.com/api/v3/picture/flags-sq-4/TUN?tx=c_fill,g_auto,q_auto,w_94,h_62",
        "team2img": "https://cloudinary.fifa.com/api/v3/picture/flags-sq-4/AUS?tx=c_fill,g_auto,q_auto,w_94,h_62",
        "team1": "Tunisia",
        "team2": "Australia",
        "cout1": 2.4,
        "coutx": 1.3,
        "Choice": "",
        "cout2": 5.4,
        "bet": 32
      },
      {
        "round": "Matchday 7",
        "group": "Group D",
        "date": "2022-11-26",
        "team1img": "https://cloudinary.fifa.com/api/v3/picture/flags-sq-4/FRA?tx=c_fill,g_auto,q_auto,w_94,h_62",
        "team2img": "https://cloudinary.fifa.com/api/v3/picture/flags-sq-4/DEN?tx=c_fill,g_auto,q_auto,w_94,h_62",
        "team1": "France",
        "team2": "Denmark",
        "cout1": 2.4,
        "coutx": 1.3,
        "Choice": "",
        "cout2": 5.4,
        "bet": 45
      },
      {
        "round": "Matchday 11",
        "group": "Group D",
        "team1img": "https://cloudinary.fifa.com/api/v3/picture/flags-sq-4/AUS?tx=c_fill,g_auto,q_auto,w_94,h_62",
        "team2img": "https://cloudinary.fifa.com/api/v3/picture/flags-sq-4/DEN?tx=c_fill,g_auto,q_auto,w_94,h_62",
        "date": "2022-11-30",
        "team1": "Australia",
        "team2": "Denmark",
        "cout1": 2.4,
        "coutx": 1.3,
        "Choice": "",
        "cout2": 5.4,
        "bet": 15
      },
      {
        "round": "Matchday 11",
        "team1img": "https://cloudinary.fifa.com/api/v3/picture/flags-sq-4/TUN?tx=c_fill,g_auto,q_auto,w_94,h_62",
        "team2img": "https://cloudinary.fifa.com/api/v3/picture/flags-sq-4/FRA?tx=c_fill,g_auto,q_auto,w_94,h_62",
        "group": "Group D",
        "date": "2022-11-30",
        "team1": "Tunisia",
        "team2": "France",
        "cout1": 2.4,
        "coutx": 1.3,
        "cout2": 5.4,
        "Choice": "",
        "bet": 63
      },
      {
        "round": "Matchday 4",
        "group": "Group E",
        "team1img": "https://cloudinary.fifa.com/api/v3/picture/flags-sq-4/GER?tx=c_fill,g_auto,q_auto,w_94,h_62",
        "team2img": "https://cloudinary.fifa.com/api/v3/picture/flags-sq-4/JPN?tx=c_fill,g_auto,q_auto,w_94,h_62",
        "date": "2022-11-23",
        "team1": "Germany",
        "team2": "Japan",
        "cout1": 2.4,
        "coutx": 1.3,
        "cout2": 5.4,
        "Choice": "",
        "bet": 53
      },
      {
        "round": "Matchday 4",
        "group": "Group E",
        "team1img": "https://cloudinary.fifa.com/api/v3/picture/flags-sq-4/ESP?tx=c_fill,g_auto,q_auto,w_94,h_62",
        "team2img": "https://cloudinary.fifa.com/api/v3/picture/flags-sq-4/CRC?tx=c_fill,g_auto,q_auto,w_94,h_62",
        "date": "2022-11-23",
        "team1": "Spain",
        "team2": "Costa Rica",
        "cout1": 2.4,
        "coutx": 1.3,
        "Choice": "",
        "cout2": 5.4,
        "bet": 43
      },
      {
        "round": "Matchday 8",
        "group": "Group E",
        "date": "2022-11-27",
        "team1": "Japan",
        "team1img": "https://cloudinary.fifa.com/api/v3/picture/flags-sq-4/JPN?tx=c_fill,g_auto,q_auto,w_94,h_62",
        "team2img": "https://cloudinary.fifa.com/api/v3/picture/flags-sq-4/CRC?tx=c_fill,g_auto,q_auto,w_94,h_62",
        "team2": "Costa Rica",
        "cout1": 2.4,
        "coutx": 1.3,
        "cout2": 5.4,
        "Choice": "",
        "bet": 42
      },
      {
        "round": "Matchday 8",
        "group": "Group E",
        "date": "2022-11-27",
        "team1img": "https://cloudinary.fifa.com/api/v3/picture/flags-sq-4/ESP?tx=c_fill,g_auto,q_auto,w_94,h_62",
        "team2img": "https://cloudinary.fifa.com/api/v3/picture/flags-sq-4/GER?tx=c_fill,g_auto,q_auto,w_94,h_62",
        "team1": "Spain",
        "team2": "Germany",
        "cout1": 2.4,
        "coutx": 1.3,
        "cout2": 5.4,
        "Choice": "",
        "bet": 35
      },
      {
        "round": "Matchday 12",
        "group": "Group E",
        "date": "2022-12-01",
        "team1img": "https://cloudinary.fifa.com/api/v3/picture/flags-sq-4/JPN?tx=c_fill,g_auto,q_auto,w_94,h_62",
        "team2img": "https://cloudinary.fifa.com/api/v3/picture/flags-sq-4/ESP?tx=c_fill,g_auto,q_auto,w_94,h_62",
        "team1": "Japan",
        "team2": "Spain",
        "cout1": 2.4,
        "coutx": 1.3,
        "cout2": 5.4,
        "Choice": "",
        "bet": 37
      },
      {
        "round": "Matchday 12",
        "group": "Group E",
        "date": "2022-12-01",
        "team1img": "https://cloudinary.fifa.com/api/v3/picture/flags-sq-4/CRC?tx=c_fill,g_auto,q_auto,w_94,h_62",
        "team2img": "https://cloudinary.fifa.com/api/v3/picture/flags-sq-4/GER?tx=c_fill,g_auto,q_auto,w_94,h_62",
        "team1": "Costa Rica",
        "team2": "Germany",
        "cout1": 2.4,
        "coutx": 1.3,
        "Choice": "",
        "cout2": 5.4,
        "bet": 37
      },
      {
        "round": "Matchday 4",
        "group": "Group F",
        "date": "2022-11-23",
        "team1img": "https://cloudinary.fifa.com/api/v3/picture/flags-sq-4/MAR?tx=c_fill,g_auto,q_auto,w_94,h_62",
        "team2img": "https://cloudinary.fifa.com/api/v3/picture/flags-sq-4/CRO?tx=c_fill,g_auto,q_auto,w_94,h_62",
        "team1": "Morocco",
        "team2": "Croatia",
        "cout1": 2.4,
        "coutx": 1.3,
        "cout2": 5.4,
        "Choice": "",
        "bet": 25
      },
      {
        "round": "Matchday 4",
        "group": "Group F",
        "date": "2022-11-23",
        "team1img": "https://cloudinary.fifa.com/api/v3/picture/flags-sq-4/BEL?tx=c_fill,g_auto,q_auto,w_94,h_62",
        "team2img": "https://cloudinary.fifa.com/api/v3/picture/flags-sq-4/CAN?tx=c_fill,g_auto,q_auto,w_94,h_62",
        "team1": "Belgium",
        "team2": "Canada",
        "cout1": 2.4,
        "coutx": 1.3,
        "cout2": 5.4,
        "Choice": "",
        "bet": 52
      },
      {
        "round": "Matchday 8",
        "group": "Group F",
        "date": "2022-11-27",
        "team1": "Belgium",
        "team1img": "https://cloudinary.fifa.com/api/v3/picture/flags-sq-4/BEL?tx=c_fill,g_auto,q_auto,w_94,h_62",
        "team2img": "https://cloudinary.fifa.com/api/v3/picture/flags-sq-4/MAR?tx=c_fill,g_auto,q_auto,w_94,h_62",
        "team2": "Morocco",
        "cout1": 2.4,
        "coutx": 1.3,
        "cout2": 5.4,
        "Choice": "",
        "bet": 14
      },
      {
        "round": "Matchday 8",
        "group": "Group F",
        "date": "2022-11-27",
        "team1img": "https://cloudinary.fifa.com/api/v3/picture/flags-sq-4/CRO?tx=c_fill,g_auto,q_auto,w_94,h_62",
        "team2img": "https://cloudinary.fifa.com/api/v3/picture/flags-sq-4/CAN?tx=c_fill,g_auto,q_auto,w_94,h_62",
        "team1": "Croatia",
        "team2": "Canada",
        "cout1": 2.4,
        "coutx": 1.3,
        "cout2": 5.4,
        "Choice": "",
        "bet": 16
      },
      {
        "round": "Matchday 12",
        "group": "Group F",
        "date": "2022-12-01",
        "team1": "Croatia",
        "team1img": "https://cloudinary.fifa.com/api/v3/picture/flags-sq-4/CRO?tx=c_fill,g_auto,q_auto,w_94,h_62",
        "team2img": "https://cloudinary.fifa.com/api/v3/picture/flags-sq-4/BEL?tx=c_fill,g_auto,q_auto,w_94,h_62",
        "team2": "Belgium",
        "cout1": 2.4,
        "coutx": 1.3,
        "cout2": 5.4,
        "Choice": "",
        "bet": 24
      },
      {
        "round": "Matchday 12",
        "group": "Group F",
        "date": "2022-12-01",
        "team1img": "https://cloudinary.fifa.com/api/v3/picture/flags-sq-4/CAN?tx=c_fill,g_auto,q_auto,w_94,h_62",
        "team2img": "https://cloudinary.fifa.com/api/v3/picture/flags-sq-4/MAR?tx=c_fill,g_auto,q_auto,w_94,h_62",
        "team1": "Canada",
        "team2": "Morocco",
        "cout1": 2.4,
        "coutx": 1.3,
        "cout2": 5.4,
        "Choice": "",
        "bet": 34
      },
      {
        "round": "Matchday 5",
        "group": "Group G",
        "team1img": "https://cloudinary.fifa.com/api/v3/picture/flags-sq-4/SUI?tx=c_fill,g_auto,q_auto,w_94,h_62",
        "team2img": "https://cloudinary.fifa.com/api/v3/picture/flags-sq-4/CMR?tx=c_fill,g_auto,q_auto,w_94,h_62",
        "date": "2022-11-24",
        "team1": "Switzerland",
        "team2": "Cameroon",
        "cout1": 2.4,
        "coutx": 1.3,
        "cout2": 5.4,
        "Choice": "",
        "bet": 14
      },
      {
        "round": "Matchday 5",
        "group": "Group G",
        "date": "2022-11-24",
        "team1img": "https://cloudinary.fifa.com/api/v3/picture/flags-sq-4/BRA?tx=c_fill,g_auto,q_auto,w_94,h_62",
        "team2img": "https://cloudinary.fifa.com/api/v3/picture/flags-sq-4/SRB?tx=c_fill,g_auto,q_auto,w_94,h_62",
        "team1": "Brazil",
        "team2": "Serbia",
        "cout1": 2.4,
        "coutx": 1.3,
        "cout2": 5.4,
        "Choice": "",
        "bet": 19
      },
      {
        "round": "Matchday 9",
        "group": "Group G",
        "team1img": "https://cloudinary.fifa.com/api/v3/picture/flags-sq-4/CMR?tx=c_fill,g_auto,q_auto,w_94,h_62",
        "team2img": "https://cloudinary.fifa.com/api/v3/picture/flags-sq-4/SRB?tx=c_fill,g_auto,q_auto,w_94,h_62",
        "date": "2022-11-28",
        "team1": "Cameroon",
        "team2": "Serbia",
        "cout1": 2.4,
        "coutx": 1.3,
        "cout2": 5.4,
        "Choice": "",
        "bet": 18
      },
      {
        "round": "Matchday 9",
        "group": "Group G",
        "date": "2022-11-28",
        "team1img": "https://cloudinary.fifa.com/api/v3/picture/flags-sq-4/BRA?tx=c_fill,g_auto,q_auto,w_94,h_62",
        "team2img": "https://cloudinary.fifa.com/api/v3/picture/flags-sq-4/SUI?tx=c_fill,g_auto,q_auto,w_94,h_62",
        "team1": "Brazil",
        "team2": "Switzerland",
        "cout1": 2.4,
        "coutx": 1.3,
        "cout2": 5.4,
        "Choice": "",
        "bet": 12
      },
      {
        "round": "Matchday 13",
        "group": "Group G",
        "date": "2022-12-02",
        "team1": "Serbia",
        "team1img": "https://cloudinary.fifa.com/api/v3/picture/flags-sq-4/SRB?tx=c_fill,g_auto,q_auto,w_94,h_62",
        "team2img": "https://cloudinary.fifa.com/api/v3/picture/flags-sq-4/SUI?tx=c_fill,g_auto,q_auto,w_94,h_62",
        "team2": "Switzerland",
        "cout1": 2.4,
        "coutx": 1.3,
        "cout2": 5.4,
        "Choice": "",
        "bet": 32
      },
      {
        "round": "Matchday 13",
        "group": "Group G",
        "date": "2022-12-02",
        "team1": "Cameroon",
        "team1img": "https://cloudinary.fifa.com/api/v3/picture/flags-sq-4/CMR?tx=c_fill,g_auto,q_auto,w_94,h_62",
        "team2img": "https://cloudinary.fifa.com/api/v3/picture/flags-sq-4/BRA?tx=c_fill,g_auto,q_auto,w_94,h_62",
        "team2": "Brazil",
        "cout1": 2.4,
        "coutx": 1.3,
        "cout2": 5.4,
        "Choice": "",
        "bet": 45
      },
      {
        "round": "Matchday 5",
        "group": "Group H",
        "team1img": "https://cloudinary.fifa.com/api/v3/picture/flags-sq-4/URU?tx=c_fill,g_auto,q_auto,w_94,h_62",
        "team2img": "https://cloudinary.fifa.com/api/v3/picture/flags-sq-4/KOR?tx=c_fill,g_auto,q_auto,w_94,h_62",
        "date": "2022-11-24",
        "team1": "Uruguay",
        "team2": "South Korea",
        "cout1": 2.4,
        "coutx": 1.3,
        "cout2": 5.4,
        "Choice": "",
        "bet": 32
      },
      {
        "round": "Matchday 5",
        "group": "Group H",
        "date": "2022-11-24",
        "team1img": "https://cloudinary.fifa.com/api/v3/picture/flags-sq-4/POR?tx=c_fill,g_auto,q_auto,w_94,h_62",
        "team2img": "https://cloudinary.fifa.com/api/v3/picture/flags-sq-4/GHA?tx=c_fill,g_auto,q_auto,w_94,h_62",
        "team1": "Portugal",
        "team2": "Ghana",
        "cout1": 2.4,
        "coutx": 1.3,
        "cout2": 5.4,
        "Choice": "",
        "bet": 34
      },
      {
        "round": "Matchday 9",
        "group": "Group H",
        "date": "2022-11-28",
        "team1img": "https://cloudinary.fifa.com/api/v3/picture/flags-sq-4/KOR?tx=c_fill,g_auto,q_auto,w_94,h_62",
        "team2img": "https://cloudinary.fifa.com/api/v3/picture/flags-sq-4/GHA?tx=c_fill,g_auto,q_auto,w_94,h_62",
        "team1": "South Korea",
        "team2": "Ghana",
        "cout1": 2.4,
        "coutx": 1.3,
        "cout2": 5.4,
        "Choice": "",
        "bet": 17
      },
      {
        "round": "Matchday 9",
        "group": "Group H",
        "date": "2022-11-28",
        "team1img": "https://cloudinary.fifa.com/api/v3/picture/flags-sq-4/POR?tx=c_fill,g_auto,q_auto,w_94,h_62",
        "team2img": "https://cloudinary.fifa.com/api/v3/picture/flags-sq-4/URU?tx=c_fill,g_auto,q_auto,w_94,h_62",
        "team1": "Portugal",
        "team2": "Uruguay",
        "cout1": 2.4,
        "coutx": 1.3,
        "cout2": 5.4,
        "Choice": "",
        "bet": 18
      },
      {
        "round": "Matchday 13",
        "group": "Group H",
        "team1img": "https://cloudinary.fifa.com/api/v3/picture/flags-sq-4/GHA?tx=c_fill,g_auto,q_auto,w_94,h_62",
        "team2img": "https://cloudinary.fifa.com/api/v3/picture/flags-sq-4/URU?tx=c_fill,g_auto,q_auto,w_94,h_62",
        "date": "2022-12-02",
        "team1": "Ghana",
        "team2": "Uruguay",
        "cout1": 2.4,
        "coutx": 1.3,
        "cout2": 5.4,
        "Choice": "",
        "bet": 39
      },
      {
        "round": "Matchday 13",
        "group": "Group H",
        "date": "2022-12-02",
        "team1img": "https://cloudinary.fifa.com/api/v3/picture/flags-sq-4/KOR?tx=c_fill,g_auto,q_auto,w_94,h_62",
        "team2img": "https://cloudinary.fifa.com/api/v3/picture/flags-sq-4/POR?tx=c_fill,g_auto,q_auto,w_94,h_62",
        "team1": "South Korea",
        "team2": "Portugal",
        "cout1": 2.4,
        "coutx": 1.3,
        "cout2": 5.4,
        "Choice": "",
        "bet": 36
      }
    ]
  }

}
